# Modify for your needs, should be an array of objects with a friendly label of what's notified and the URL to scrape
sites:
  -
    label: Vaterschaftsanerkennung
    type: berlin_service
    params:
      url: https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=122900&anliegen[]=318991&herkunft=1
  -
    label: Geburtsurkunde
    type: berlin_service
    params:
      url: https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=122900&anliegen[]=318957&herkunft=1

# Set true to allow multiple notifications for the same appointment instead of just the first
allow_multiple_notifications: false

# Configure for ntfy support
ntfy:
  server: ~ # Leave blank to use default https://ntfy.sh
  topic: ~

# Configure for pushbullet support
pushbullet:
  api_token: ~

# Configure for telegram support
telegram:
  api_key: ~
  chat_id: ~

# Logger configuration
logger:
  level: info
  log_to_file: false # If true will log to file as well as stdout

# Configure trigger rules
rules:
  -
    type: after
    param: PT48H # At least 48h notice, uses PHP DateInterval construct. See: https://www.php.net/manual/en/dateinterval.construct.php
  -
    type: before_date
    param: '2025-04-09 23:59:59' # Before Easter break
  -
    type: after_date
    param: '2025-04-28 00:00:00' # After Easter break
