service: app
frameworkVersion: '4'

provider:
    name: aws
    region: eu-west-1

plugins:
    - ./vendor/bref/bref

functions:
    termin:
        handler: function.php
        description: 'Simple PHP script for notifying for a free appointments on the Berlin services website'
        runtime: php-83
        architecture: arm64
        events:
          - schedule: cron(0 * * * ? *)
          - schedule: cron(*/15 07-10 * * ? *)

package:
    patterns:
        - '!tests/**'
        - '!node_modules/**'
