name: CI
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: |
          ./vendor/bin/phpunit
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: inversechi/termin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


