name: CI
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.2']
    steps:
    - uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: |
        ./bin/phpunit --coverage-clover coverage.xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php7.2
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: PHPStan
        run: phpstan analyse

