name: CI
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '7.3', '7.2']
    steps:
    - uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install dependencies
      run: composer install
    - name: Run unit tests
      run: ./vendor/bin/phpunit
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php7.4
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: PHPStan
        run: phpstan analyse

