name: CI
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.2', '8.1']
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: |
        XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml
    - uses: codecov/codecov-action@v4
      if: matrix.php-version == '8.3'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install
      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix
